export enum OAuthApprovalState {
  PENDING = 'PENDING',
  BOUND = 'BOUND',
  REVOKED = 'REVOKED',
}

export enum OAuthAuthenticationAuditAction {
  IDENTITY_BOUND = 'IDENTITY_BOUND',
  LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED',
  LOGIN_DENIED = 'LOGIN_DENIED',
  APPROVAL_GRANTED = 'APPROVAL_GRANTED',
  APPROVAL_REVOKED = 'APPROVAL_REVOKED',
  BINDING_RESET = 'BINDING_RESET',
  COMMAND_DENIED = 'COMMAND_DENIED',
}

export enum OAuthAuthenticationAuditOutcome {
  SUCCESS = 'SUCCESS',
  DENIED = 'DENIED',
}
